name: Actualizar TRMNL Banxico

on:
  schedule:
    # 1. Apertura (8:00 AM CDMX es 14:00 UTC)
    - cron: '0 14 * * *'
    
    # 2. Cierre/Post-FIX (3:00 PM CDMX es 21:00 UTC)
    - cron: '0 21 * * *'
  
  workflow_dispatch: # Para que puedas picar el botón manualmente si quieres

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías necesarias
        run: pip install requests yfinance pytz

      - name: Ejecutar el script main.py
        env:
          TRMNL_WEBHOOK_URL: ${{ secrets.TRMNL_WEBHOOK_URL }}
        run: python main.py
